# Orchestration mode runtime configurations

shard.Pair.Model.List:
            -  shardId: 1
               masterIp: "localhost:3306"
               slaveIp:  "localhost:3306"
               startKey: "00"
               endKey:   "ff"



flux.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux?autoReconnect=true&useSSL=false"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 3
  hibernate.c3p0.max_size: 10


fluxReadOnly.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux?autoReconnect=true&useSSL=false"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 3
  hibernate.c3p0.max_size: 5

flux_scheduler.Hibernate:
  hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
  hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
  hibernate.connection.url: "jdbc:mysql://localhost:3306/flux_scheduler?autoReconnect=true&useSSL=false"
  hibernate.connection.username: "root"
  hibernate.connection.password: ""
  hibernate.current_session_context_class: "managed"
  connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
  hibernate.c3p0.min_size: 3
  hibernate.c3p0.max_size: 20

Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30

Api:
  service.port: 9998
  service.acceptors: 4
  service.selectors: 4
  service.workers: 100


redriver:
  batchDelete:
    batchSize: 1000
    intervalms: 2500
  batchInsert:
    batchSize: 200
    intervalms: 200
  batchRead:
    batchSize: 1000
    intervalms: 2500
  noOfPersistenceWorkers: 20

eventScheduler:
  batchRead:
    batchSize: 50
    intervalms: 1000

runtime:
  actorsystem:
    metrics: false
    name: FluxOrchestrationSystem
    configname: orchestration_akka.conf

task:
  maxTaskRetryCount: 10

elbCache:
  maxSize: 50

eventProxyForMigration:
  enabled: "no"
  endpoint: "http://localhost:9998/api/machines"

connector:
  max.connections: 100
  max.connections.per.route: 25
  connection.timeout: 10000
  socket.timeout: 10000

enableAuditRecord: True